### ISSUE TITLE
Create play all feature (stitching/ playlist)

### ISSUE THREAD

**Issue by AlexHandy1** [snapchidu/stitchvid#10]
- v0.1 create playlist of all videos
- explore stitching based on R&D

**Comment by DanielJohnston** [comment]
Exploring sending a playlist to YouTube as a first version solution.

**Comment by DanielJohnston** [comment]
First version solution has been copy-pasted out of branch and into Alex & Chidu's. Requires some way of storing or generating a playlist, e.g. using tags, to pass to the code.
